---
title: "GRSS VEDA Docs"
subtitle: "How to use VEDA services"
---

## Welcome {#welcome}


**_IEEE GRSS has deployed VEDA_** (Developed by NASA's Earth Science Data Systems (ESDS) Program) as a platform for the GRSS community to share and access data, stories, and example code for geospatial data analysis and visualization.

VEDA ([Visualization, Exploration and Data Analysis](https://www.earthdata.nasa.gov/esds/veda)) is a redeployable data platform to support scientific visualization and analysis.

By combining interactive storytelling with open science principles, VEDA enables researchers to engage new audiences and share their analysis results effectively.

These docs help you use the services provided by the NASA VEDA Platform and learn about the open-source software ecosystem that it is based on.

## Checkout the notebooks

### Datasets
- [Wetland Methane Emissions, LPJ-EOSIM Model](user-guide/notebooks/datasets/lpjeosim-wetlandch4-monthgrid-v1_User_Notebook.ipynb)

### Quickstart guides
- [Getting Started with VEDA](user-guide/notebooks/quickstarts/list-collections.ipynb)
- [Download Assets](user-guide/notebooks/quickstarts/download-assets.ipynb)
- [Map plot](user-guide/notebooks/quickstarts/no2-map-plot.ipynb)
- [Map plot](user-guide/notebooks/quickstarts/timeseries-stac-api.ipynb)


## New to VEDA?

Learn more about VEDA from its documentation at [docs.openveda.cloud](https://docs.openveda.cloud).